apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chamo-app-to-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://172.18.8.10:6443
  template:
    metadata:
      name: '{{ cluster }}-chamo-app'
      labels:
        app: chamo-kustomize
    spec:
      syncPolicy:
        automated: {}
      project: default
      source:
        repoURL: https://github.com/alvarolinarescabre/fastapi-get-href-10-websites-kustomize.git
        targetRevision: HEAD
        path: '.'
        kustomize: {}
      destination:
        cluster: '{{ url }}'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=true
