apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chamo-app-to-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/alvarolinarescabre/fastapi-get-href-10-websites-argocd-applicationsets.git
        revision: HEAD
        files:
          - path: "config/fastapi-config.json"
        template:
          metadata:
            name: '{{ name }}'
            labels:
              app: chamo-kustomize
          spec:
            syncPolicy:
              automated: {}
            project: '{{ project }}'
            source:
              repoURL: https://github.com/alvarolinarescabre/fastapi-get-href-10-websites-kustomize.git
              targetRevision: HEAD
              path: '.'
              kustomize: {}
            destination:
              name: '{{ cluster.name }}'
              namespace: '{{ namespace }}'
  template:
    metadata:
      name: '{{clusterName}}-chamo-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/alvarolinarescabre/fastapi-get-href-10-websites-kustomize.git'
        targetRevision: HEAD
        path: '.'
      destination:
        name: '{{clusterName}}'
        namespace: fastapi-app
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
