apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chamo-app-to-apps
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{clusterName}}-chamo-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/alvarolinarescabre/fastapi-get-href-10-websites-kustomize.git'
        targetRevision: HEAD
        path: '.'
      destination:
        name: '{{clusterName}}'
        namespace: fastapi-app
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
