apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chamo-app-to-apps
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: chamo-app-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{clusterName}}-chamo-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/alvarolinarescabre/fastapi-get-href-10-websites-kustomize.git'
        targetRevision: HEAD
        path: '.'
      destination:
        name: '{{clusterName}}'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
